language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - memcached


before_script:
  - cd tests
  - mysql -e 'create database malmo_test;'
  - echo "<?php return array();" > config-local.php

script: phpunit --colors --no-globals-backup malmo/
