<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
'Your Setup is unrealistic and way out of Limits' => 'Нереалистичная конфигурация, но не факт!',
  'No title' => 'Без названия',
  'Continuos current per motor {cur}A is more than ESC current' => 'Средний ток на моторе {cur}A превышает номинальный ток на ESC',
  'Deca (10 rotors)' => 'Дека (10 моторов)',
  'For good maneuverability you need Throttle of less than 80%' => 'Уровень газа превышает 80%, будет паршивая маневренность',
  'Hexa' => 'Гекса',
  'Max current per motor {cur}A is more than ESC current' => 'Максимальный ток на моторе {cur}A превышает максимальный ток ESC',
  'Octo' => 'Окто',
  'Prop RPM limit is {pm}, motor max RPM is {p}. Please, be careful' => 'Максимальные обороты пропеллера {p} превышают рекомендованные производителем {pm}, возможно разрушение пропеллера',
  'Prop will stall, calculation for hovering not possible! (reduce Pitch)' => 'Проверьте данные пропеллеров, расчет невозможен',
  'Quad' => 'Квадрик',
  'The Power is not sufficient to hover' => 'Не хватает мощности для висения, чтото не то с конфигурацией',
  'Tri' => 'Треха',
  'Your propeller values (Twist and Pitch) resulting in a negative propeller pitch' => 'Данные пропелелера дают отрицательный шаг, проверьте правильность ввода',
  'max. current over the limit of the battery' => 'Максимальный ток превышает допустимый для батареи',
  'max. current over the limit of the motor. Please verify the limits (current, power, rpm) defined by the manufacturer!' => 'Максимальный ток мотора превышает допустимый. Проверьте данные.',
  'the prediction of the motor case temperature is critical (>80C). Please check!' => 'Моторы могут греться выше 80С',
  'Max. power over the limit of the motor. Please check the limits!' => 'Превышение максимальной мощности на моторе, проверьте лимиты!',
);
