<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '{user} doesn\'t have any copters' => 'У {user} пока что нет коптеров',
  'Copters' => 'Коптеры',
  'Easy way to calculate you rc model' => 'Простой способ расчитать ваш коптер',
  'Edit your profile' => 'Редактировать профиль',
  'Login' => 'Вход в систему',
  'Login in Rc Calc without any registration' => 'Войти в Rc Calc без регистрации',
  'Rc Calc is the simpliest way to calculate your RC Copter.We can help you with bulding any type of copters.
        We can help you with bulding any type of copters.You can share you calc and save in you profile.' => 'С помощью Rc Calc вы легко можете расчитать параметры вашего будущего коптера и подобрать наиболее оптимальные.
        Также вы можете дать ссылку на ваш расчет и сохранить его у себя в профиле.',
  'We calculate now' => 'Мы уже расчитали ',
  'You have no copter calcs, please' => 'У вас сейчас нет расчетов коптеров, ',
  'You need to login' => 'Вам необходимо зайти в систему',
  'Your Profile' => 'Мой профиль',
  'add one' => 'добавьте новый',
  'model|models' => 'модель|модели|моделей|моделей',
);
