<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'City' => 'Город',
  'Login into Rc Calc' => 'Войти в Rc Calc',
  'Please update you profile' => 'Пожалуйста, заполните Ваш профиль',
  'Please, click on icon where you are. You will be automaticaly login in system without any registration'
    => 'Нажмите на иконку сайта, где вы зарегестрированы. Вы автоматически войдете в систему',
  'This username have another user' => 'Это имя занято другим пользователем',
  'Username can have only "a-z - _"' => 'Может содержать только англ. буквы и символы -_',
  'Your page URL' => 'Ваша страница',
);
